### ISSUE TITLE
Logstash - Update broke the config

### ISSUE THREAD

**Issue by bntjah** [zeropingheroes/lancache-elk#10]
Just noticed that upon installing on a newer system (Ubuntu 18.04) that the newer logstash has some issues with beat names. But I haven't been able to correctly fix it yet; perhaps somebody here has a better idea?

Its not really Ubuntu 18.04 related but more of an update from Logstash that broke the config?

**Comment by ilumos** [comment]
Hey! Can you give a bit more info on this - haven't been able to reproduce doing a quick test in Vagrant

**Comment by bntjah** [comment]
Hey Ilumos,

At first glances it seems that the logs aren't correctly written within logstash.
So Kibana dashboard doesn't show the correct data as its not in the right "tables"...

I think I have the VM still on my machine at home so I will check later on...
And will post back here sorry for the longer wait time...
