### ISSUE TITLE
Problems setting up everything on one VM

### ISSUE THREAD

**Issue by ScholliYT** [zeropingheroes/lancache-elk#2]
So I just made a fresh ubuntu server 16.04 VM and installed Lancache with this script: https://github.com/zeropingheroes/lancache-installer

I also added the sniproxy and the dns provided by zeropingheroes. Seems to be working fine 👍 

So then I went on to add this repo. Installation was easy too. After enabling remote acces (from other computer in my local network) onto the VM I was able to login to the webinterface. Then I added the saved Object as explained in the read.me. So there was an error and I went to this [page](http://prntscr.com/kfvd23). I "fixed" it by using "logstash-*" as index pattern. Then I picked "@timestamp" as Time filter field name. 

So the diagrams are not loading and just throwing erros: "Could not locate that visualization (id: 44df61e0-0546-11...)"

also it seems like installing kibana on the same VM broke the lancache. When I try to start a download in steam it instantly cancels. Is kibana running something on port 80?

**Comment by ilumos** [comment]
Hi there,

Yep some part of ELK runs on port 80 - not sure which bit. 

Did Kibana ask if you wanted to fix the indexes when you imported the `export.json`?

Cheers

**Comment by ScholliYT** [comment]
After setting it now up on two seperate linux machines Kibana didn't ask to fix indexes. Instead it suggested "logstash-*" as index. See [here](http://prntscr.com/kfxrlu). 

I added a new PR with some more information on how to set the system up.
