### ISSUE TITLE
Could not locate that visualisation

### ISSUE THREAD

**Issue by marcusboon** [zeropingheroes/lancache-elk#4]
Hi, I installed the pre-reqs (lancache, lancache-filebeat) and followed the instructions to import the export.json choosing to resolve the "New index pattern" as "logstash-*". But its giving me "visualisation not found errors" when viewing the dashboard.

Should probably note that I'm on Ubuntu 18.04 and I had to install java manually to get logstash to install. The install.sh would fail with:
`Preparing to unpack .../logstash_1%3a6.4.0-1_all.deb ...
Unpacking logstash (1:6.4.0-1) ...
Setting up logstash (1:6.4.0-1) ...
Using provided startup.options file: /etc/logstash/startup.options
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
chmod: cannot access '/etc/default/logstash': No such file or directory
dpkg: error processing package logstash (--configure):
 installed logstash package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 logstash
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

![kibana](https://user-images.githubusercontent.com/3231180/45491988-73cff080-b7ae-11e8-8ef6-97b05fb1548f.PNG)

**Comment by ilumos** [comment]
Hey there,

If you do the import again, it should work in my experience.

Not exactly sure what's going on but I will investigate.

Many thanks

**Comment by marcusboon** [comment]
Hi @ilumos it seems like I just had to wait a bit for it to pick it up. It's working now, although the "known issue" makes it hard to determine how much has actually been added to the cache and how much has been served from the cache. No big deal though.

**Comment by ilumos** [comment]
Ah ok good to know - thanks for sharing.
