### ISSUE TITLE
lil help on the documentation pls?

### ISSUE THREAD

**Issue by billthecatt** [zeropingheroes/lancache-elk#5]
Hey, 

(Please pardon my ignorance on how filebeat ties in to this solution. )
So I have my lancache server running ok, and my kibana installed without a flaw, the import of the config worked great. I'm looking forward to having some better reporting on what's going on with the cache data itself.

What I don't quite understand is what I'm supposed to be doing with filebeat once its installed on my lancache server. I followed the instructions provided with lancache-filebeat and what I'm missing is what the host I'm supposed to point to in the last few steps should be. Is it the elk server? If so, I wasn't seeing a 5044 port open there. Should I specify another port?  I get the feeling that filebeat is the middleware that somehow gets the logs off the lancache server and onto the elk server, but I'm not clear as to how the logs actually do get from the lancache server to the elk server to be processed.

I should mention that I installed elk, kibana and lancache-elk on a debian server instead of the ubuntu server specified. Wondering if there's some base component of ubuntu I'm missing out on by not using ubuntu, but I speak deb so, I'm hopeful I can still make it work.

Can someone please clarify? TYVM for this project btw, nice stuff!

**Comment by ilumos** [comment]
Hi there!

Thanks for your interest in the project - here's a useful image:

https://logz.io/wp-content/uploads/2017/06/relationship-between-filebeat-and-logstash.png

Filebeat hoovers up lines as they're written by nginx to the log files on your cache server, and ships them to logstash, which separates each part of the log line into IP, date, URL etc, and then logstash ships that to elasticsearch. Kibana then reads data out of elasticsearch and visualises it.

Check that logstash is enabled and running:

`$ systemctl status logstash`

Check that the lancache logstash config exists:

`$ cat /etc/logstash/conf.d/lancache-pipeline.conf`

Check that logstash is listening on port 5044/tcp:

`$ lsof -i :5044`

Hope this helps!

**Comment by billthecatt** [comment]
This is perfect.  I've now got logstash working on the elk server. (Might want to add that as a requirement on the ELK server. It's not installed by default for debian kibana installs for whatever reason.)

Thanks very much for the DL on what I was missing.

**Comment by ilumos** [comment]
Great stuff, glad you got it working :)
